// Generated by Wrangler by running `wrangler types`

interface Env {
	PORKBUN_AAAA_RECORD: "home";
	USER: string;
	PASSWORD: string;
	PORKBUN_API_KEY: string;
	PORKBUN_SECRET_API_KEY: string;
	PORKBUN_DOMAIN: string;
	PORKBUN_A_RECORD: string;
}
