// Generated by Wrangler by running `wrangler types`

interface Env {
	PORKBUN_DOMAIN: "example.com";
	PORKBUN_A_RECORD_ID: "1234";
	PORKBUN_AAAA_RECORD_ID: "1234";
	USER: string;
	PASSWORD: string;
	PORKBUN_API_KEY: string;
	PORKBUN_SECRET_API_KEY: string;
}
